In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.arange(10, 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

## Indexing

In [4]:
## Get 15 in the output

arr[5]

15

In [5]:
## Get 20 in the output

arr[10]

20

In [6]:
arr[-5]

20

In [7]:
arr[100]

IndexError: index 100 is out of bounds for axis 0 with size 15

## Slicing

- Get the sub array out of the original array is called slicing

In [9]:
## Get the output [15, 16, 17, 18, 19, 20]

arr[5:11]

array([15, 16, 17, 18, 19, 20])

In [10]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr[5:11:2]

array([15, 17, 19])

## Array Creation

In [12]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

In [13]:
arr2 = np.array([10, 20, 25.7, 40, 50])
arr2

array([10. , 20. , 25.7, 40. , 50. ])

- Array perform an implicit conversion of data types, as the array can contain only 1 data type values inside it

In [14]:
arr3 = np.array([10, 20, 25.7, 40, 'Bombay'])
arr3

array(['10', '20', '25.7', '40', 'Bombay'], dtype='<U32')

In [15]:
arr4 = np.array([1, 2, 3.0, 4, 5])
arr4

array([1., 2., 3., 4., 5.])

## Arithematic Operations on an array

In [16]:
arr1

array([10, 20, 30, 40, 50])

In [18]:
arr = np.array([100, 200, 300, 400, 500])
arr

array([100, 200, 300, 400, 500])

In [19]:
## Addition 
arr + arr1

array([110, 220, 330, 440, 550])

- Addition operation on 2 arrays perform an element wise addtion

In [20]:
arr1

array([10, 20, 30, 40, 50])

In [21]:
## Multiplication 

arr1 * 3

array([ 30,  60,  90, 120, 150])

- Broadcasting operation of the number 3 on the all the elements of the array

In [22]:
## Division

arr1

array([10, 20, 30, 40, 50])

In [23]:
arr1 / 2   ## Broadcasting operation

array([ 5., 10., 15., 20., 25.])

In [24]:
l1 = [10, 20, 30, 40]
l1 / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [25]:
arr1

array([10, 20, 30, 40, 50])

In [27]:
arr

array([100, 200, 300, 400, 500])

In [28]:
## Subtraction operation

arr - arr1

array([ 90, 180, 270, 360, 450])

In [29]:
## Adding with one number to all the values of an array

arr1 + 5

array([15, 25, 35, 45, 55])

In [30]:
arr1

array([10, 20, 30, 40, 50])

In [32]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

## Conditional Indexing or Boolean Indexing

In [48]:
arr = np.random.randint(50, 500, 20)
arr

array([ 62, 403, 347, 464,  79,  98, 351, 377, 267, 488, 413, 173, 271,
       301, 251, 464, 165, 106, 332, 317])

In [38]:
## Get an output where the numbers of the array are even nos

100 % 2

0

In [39]:
100 % 2 == 0

True

In [40]:
arr % 2 == 0

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False, False])

In [49]:
arr[(arr % 2 == 0)]

array([ 62, 464,  98, 488, 464, 106, 332])

In [43]:
arr

array([121, 263, 245, 194, 126,  60, 278, 212, 416, 174, 325, 434, 237,
       142, 488, 304, 310, 390, 161, 251])

In [50]:
## Get all odd nos in the output

arr[(arr % 2 != 0)]

array([403, 347,  79, 351, 377, 267, 413, 173, 271, 301, 251, 165, 317])

In [51]:
arr

array([ 62, 403, 347, 464,  79,  98, 351, 377, 267, 488, 413, 173, 271,
       301, 251, 464, 165, 106, 332, 317])

In [52]:
## Get all the numbers which are divisible by 5

arr[(arr % 5 == 0)]

array([165])

## 

In [53]:
arr = np.arange(125, 250)
arr

array([125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249])

In [54]:
## get all the number divisible by 10 from arr

arr[(arr % 10 == 0)]

array([130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [57]:
## Get all the number divisible by 3 and divisble by 5

arr[(arr%3==0) & (arr%5==0)]

array([135, 150, 165, 180, 195, 210, 225, 240])

In [63]:
## Get all prime numbers from the array

for i in range(len(arr)):
    if arr[(arr % 1 == 0) & (arr % arr == 0)]:
        print(arr[i])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [66]:
arr

array([125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249])

## Indexing

In [67]:
arr = np.array([10, 20, 'Anil', 'Bombay'])
arr

array(['10', '20', 'Anil', 'Bombay'], dtype='<U11')

In [68]:
arr[1]

'20'

In [69]:
# Get 'Anil' in the output

arr[2]

'Anil'

In [71]:
## Get n from Anil in the output

arr[2][1]

'n'

In [72]:
## Get y from Bombay in the output

arr

array(['10', '20', 'Anil', 'Bombay'], dtype='<U11')

In [74]:
arr[-1][-1]

'y'

## 2D array

In [75]:
l1 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
l1

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [76]:
arr1 = np.array(l1)
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [78]:
arr1.ndim  ### ndim - stands for number of dimensions

2

In [79]:
arr

array(['10', '20', 'Anil', 'Bombay'], dtype='<U11')

In [80]:
arr.ndim

1

In [81]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Index a 2D array

In [82]:
arr1[0]

array([10, 20, 30])

In [83]:
arr1[2]

array([70, 80, 90])

In [85]:
## Get 20 in the output 

arr1[0][1]

20

In [86]:
## Get 50 in the output

arr1[1][1]

50

In [87]:
arr1[1, 1]

50

In [88]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
arr1[1, 0]

40

In [90]:
arr1[2, 1]

80

In [96]:
arr = np.arange(5, 25)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [97]:
arr.ndim

1

In [100]:
## Convert the above array into a 2D array

arr.reshape(5, 4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [101]:
arr.reshape(4,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
arr.reshape(10, 2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [103]:
arr.reshape(2, 10)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [107]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [108]:
## Convert 2D array into 1D array

arr1.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
arr1.ravel()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## To tell me the difference between flatten() and ravel()?